name = "options-insight"
main = "src/index.js"
compatibility_date = "2024-05-01" # Updated to a more recent date

# This section defines environment variables that will be injected 
# into the Cloudflare worker's 'env' object.
[vars]
# This binds the GitHub/Cloudflare Secret (FINNHUB_API_KEY)
# so it can be accessed inside Cloudflare worker code as env.FINNHUB_API_KEY
FINNHUB_API_KEY = "{{ FINNHUB_API_KEY }}"

[triggers]
crons = ["0 8 * * 1-5"]