name = "options-insight"
main = "src/index.js"
compatibility_date = "2024-05-01" # Updated to a more recent date

# This section defines non-sensitive environment variables that will be injected 
# into the Cloudflare worker's 'env' object.
#
# IMPORTANT: Do NOT put secrets here. Use `wrangler secret put` (or `make push-secrets`)
# for values like FINNHUB_API_KEY, RESEND_API_KEY, GEMINI_API_KEY, etc.
[vars]

[triggers]
crons = ["0 10 * * 1-5"]
