blank_issues_enabled: false
contact_links:
  - name: Security or vulnerability disclosure
    url: https://github.com/ravishan16/options-insight#security-policy
    about: Please review the security policy before reporting vulnerabilities.
