name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      - name: Validate config and secrets hygiene
        run: node validate-config.js
        
      - name: Run tests with coverage
        run: npm run test:coverage
        # Tests are fully mocked; do not pass real secrets.
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      - name: Validate config and secrets hygiene
        run: node validate-config.js
        
      - name: Validate Wrangler configuration
        run: npx wrangler types
        
      - name: Check for TypeScript/ESLint issues
        run: |
          # Validate JS syntax and imports
          node -c src/index.js
          node -c src/simplified-data.js
          node -c src/real-volatility.js
          node -c src/email.js
          echo "✅ All core modules have valid syntax"
