name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    name: Smoke Test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm test
      - name: Print Wrangler version
        run: npx wrangler --version
      - name: Dry-run compile
        run: npx wrangler deploy --dry-run --outdir=./.wrangler/dry-run

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: smoke-test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm test
      - name: Print Wrangler version
        run: npx wrangler --version
      - name: Deploy
        run: npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
