name: Pull Request Checks

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      - name: Validate config and secrets hygiene (non-strict)
        run: node validate-config.js
        
      - name: Run tests with coverage
        run: npm run test:coverage
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          
      - name: Print Wrangler version
        run: npx wrangler --version
        
      - name: Dry-run compile
        run: npx wrangler deploy --dry-run --outdir=./.wrangler/dry-run
