name: Pull Request Checks

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Print Wrangler version
        run: npx wrangler --version
      - name: Dry-run compile
        run: npx wrangler deploy --dry-run --outdir=./.wrangler/dry-run
